# Site settings
title: JM McGhee
description: A Blog anf
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://owlman77.github.io/
# User settings
username: Jean-Marc McGhee
user_description: WIP
user_title: Web Developer
email: jeanmarc.mcghee@gmail.com
twitter_username: jeanmarc_mcghee
github_username:  Owlman77
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
