# Site settings
title: JM McGhee
description: A Blog and Portfolio of Jean-Marc McGhee
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://owlman77.github.io/
# User settings
username: Jean-Marc McGhee
user_description: I've always been curious and eager to learn. I studied science because I enjoyed exploring the complex structure of life, and I studied cooking because I wanted to know the techniques to make my favourite foods, but there was always something missing. The thing I enjoy most with development is that there's always something new to learn and you see the solid result of your work in front of you. For me, full stack is where my true interests lie as it fulfils that curiosity in me to see the whole process in the work. My ideal environment would be a close-knit team in which I would be able to see the organism that is code in full motion.
user_title: Web Developer
email: jeanmarc.mcghee@gmail.com
twitter_username: jeanmarc_mcghee
github_username:  Owlman77

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
